config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'photo' => 'static_pages#photo'

  get 'photo2' => 'static_pages#photo2'
  
  get 'map' => 'static_pages#map'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><span class="glyphicon glyphicon-home"><%=  link_to "home", root_path %></span></li>
      <li><span class="glyphicon glyphicon-picture"><%= link_to "photo ", photo_path %></span></li>
      <li><span class="glyphicon glyphicon-globe"><%= link_to "access ", map_path %></span></li>
      <li><span class="glyphicon glyphicon-envelope"><%= link_to "contact", "#" %></span></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hanakawa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
     <% flash.each do |message_type, message|%> 
    <%= content_tag(:div, message, :class => "alert alert-#{message_type}")%>
    <% end %>
  </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    

</body>
</html>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h1> Hanakawa Rooms</h1>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="welcome">
	Welcome to the Hanakawa renting room service.
      </div>  
      <div class="about">
	The Hanakawa house is located in a residential aera on the North part of the Osaka city. In this house you may find all the confort that you need for short trip in the Kansai or an accomodation for a short stay period.
      </div>
    </div>
  </div>
</div>

app/views/static_pages/map.html.erb
<h1>How to go the Hanakawa House</h1>


<aside>
  <div class="adress_info">
    Osaka Nishiyodogawa 
  </div>
</aside>


<div id="map-container">
</div>

<div class="col-md-8 col-md-offset-2">
  <%= link_to "From Tsukamoto Station", class: "btn btn-lg btn-primary" %>

</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAx9LvlDhAVvryS6WVQWEH6v2y_e9FD49Y&callback=initMap" async defer></script>

app/views/static_pages/photo.html.erb
<div class="col-md-6 col-md-offset-3">  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
	<%= link_to image_tag("elizabeth.jpeg") %>
      </div>

      <div class="item">
	<%= link_to image_tag("Crystal_128_penguin.jpeg") %>
      </div>
      
      <div class="item">
	<%=  link_to image_tag("interior-design-36.jpg") %>
      </div>
      
      <div class="item">
	<img src="">
      </div>
    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/static_pages/photo2.html.erb
<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
	<img src="elizabeth.jpeg" alt="Elizabeth" width="460" height="345">
      </div>
      
      <div class="item">
	<img src="Crystal_128_penguin.jpeg" alt="Penguin" width="460" height="345">
      </div>

      <div class="item">
	<img src="interior-design-36.jpg" alt="Interior" width="460" height="345">
      </div>

      <div class="item">
	<img src="img_flower2.jpg" alt="Nothing" width="460" height="345">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>